@startuml
left to right direction
skinparam packageStyle rectangle
actor ユーザ
rectangle ToDo管理アプリ {
  ユーザ -- (ToDo作成)
  (ToDo作成) .> (カテゴリ選択)
  ユーザ -- (完了状態管理)
  ユーザ -- (一覧表示)
  (一覧表示) .> (キーワード検索)
  (一覧表示) .> (カテゴリ検索)
  (一覧表示) .> (ページング)
  ユーザ -- (削除)
  ユーザ -- (一括削除)
  ユーザ -- (カテゴリ作成)
  ユーザ -- (サンプルデータ復元)
}
@enduml